version: "2"
services:
  qbay-cli:
    image: your_docker_hub_name/your_docker_hub_repo_name:version_info
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
      - qbay-db
    links:
      - qbay-db
    environment:
      - db_string=mysql+pymysql://root:root@qbay-db/qa327
    # command:  ["./wait-for-it.sh", "qbay-db:3306", "--strict" , "--timeout=300", "--", "python", "-m", "qbay"]
    networks:
      - qbay-site
  
  qbay-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --init-file /data/application/init.sql
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db_init.sql:/data/application/init.sql
    networks:
      - qbay-site
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on: 
      - qbay-db
    environment:
      PMA_HOST: qbay-db
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8082:80
    networks:
      - qbay-site

networks:
  qbay-site: